title: Bryant Technology Solutions
description: Your Personal IT Department
url: https://bryanttechsolutions.com
baseurl: ""

markdown: kramdown
theme: null

sass:
  style: compressed

plugins:
  - jekyll-sitemap
